### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-dev#23]
**Is your feature request related to a problem? Please describe.**
Currently, there is no favicon in the website.

**Describe the solution you'd like**
Add a favicon.

**Screenshots**

![image](https://user-images.githubusercontent.com/97069900/151163747-508ce194-984a-40fb-b5e9-2f53be520aed.png)

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Sure! @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
Thank you @Piumal1999
