### ISSUE TITLE
Need to fix the year of the footer 

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [sef-global/sef-dev#26]
**Describe the bug**
The year that in footer is not 2022 . It is 2021

**To Reproduce**
1. Go to 'https://dev.sefglobal.org/'
2. Scroll down to 'footer'

**Expected behavior**
It should 2022 .

**Screenshots**
![image](https://user-images.githubusercontent.com/90438593/151665994-774a1200-9976-4bf9-aa07-0e99024d9a6c.png)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome

**Additional context**
N/A

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Yeah @VishwaAmarasinghe. You can add a script to display the current year automatically
