### ISSUE TITLE
Take the footer icons in the mobile view to the center

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-dev#32]
**Is your feature request related to a problem? Please describe.**
Currently when in the mobile view there it is aligned to the right

**Describe the solution you'd like**
Take the footer icons in the mobile view to the center

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/151703077-22ababbd-0f53-4ab1-a937-7dbefa733887.png)

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

sure
