### ISSUE TITLE
Add a Screenshot topic to the feature request template

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-dev#33]
**Is your feature request related to a problem? Please describe.**
Currently there is no screenshot topic in the feature request template

**Describe the solution you'd like**
Add a Screenshot topic to the feature request template

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
@YoshithaRathnayake Thanks for your suggestion. I think we don't need the screenshot section for the feature request template. But for the bug report template, it should be there.

**Comment by YoshithaRathnayake** [comment]
So can you assign me
