### ISSUE TITLE
Add a link to the nav logo in sef dev site

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-dev#34]
**Is your feature request related to a problem? Please describe.**
Currently there is no link in the nav logo

**Describe the solution you'd like**
Add a link to the nav logo in sef dev site

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/151703226-fec9beb9-bcc3-4056-a737-499999f389fe.png)

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Good suggestion @YoshithaRathnayake 
Which page are we going to link with that logo?

**Comment by YoshithaRathnayake** [comment]
Same page if you have a suggestion tell me

**Comment by Piumal1999** [comment]
> Same page

Ok @YoshithaRathnayake. You can use the dev.sefglobal.org page url

Btw we currently have only one page(home page) on the dev-site. So this button will just refresh the same page

**Comment by YoshithaRathnayake** [comment]
Yeah but it is better than the current one no?
