### ISSUE TITLE
The title and the sentence are link sticked to each

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-dev#35]
**Describe the bug**
Currently the title and the sentence are link sticked to each

**To Reproduce**
1. Go to ['Dev Team Site'](https://dev.sefglobal.org/)
3. Scroll down to 'Welcome Pull Request'

**Expected behavior**
Add a margin between them

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/151703355-45f93eaa-f42c-46a9-b2cd-c9ac2da3af0d.png)

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
@YoshithaRathnayake I couldn't reproduce this bug. Is it in the mobile view? (If so, could you please add the dimensions)

**Comment by YoshithaRathnayake** [comment]
No in all views @Piumal1999

**Comment by DilinaBandara** [comment]
@anjula-sack Can you please assign me to this if possible?
I would like to work on it

**Comment by YoshithaRathnayake** [comment]
> @anjula-sack Can you please assign me to this if possible? I would like to work on it

So I didn't do this still because anyone didn't assigned me

**Comment by anjula-sack** [comment]
@YoshithaRathnayake I couldn't reproduce this bug. Is this still there?

**Comment by YoshithaRathnayake** [comment]
Yes @anjula-sack can't you see that
