### ISSUE TITLE
Add a hover effect to the links in the navbar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-dev#36]
**Is your feature request related to a problem? Please describe.**
Currently there is no hover effect in the links of the navbar

**Describe the solution you'd like**
Add a hover effect to the links in the navbar

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
@YoshithaRathnayake are you working on this?

**Comment by YoshithaRathnayake** [comment]
Yes but no one assign me @anjula-sack

**Comment by YoshithaRathnayake** [comment]
So according to the sef best practises I can't contribute to this until some one assign me

**Comment by anjula-sack** [comment]
sorry @YoshithaRathnayake I saw this now. Go ahead

**Comment by YoshithaRathnayake** [comment]
> sorry @YoshithaRathnayake I saw this now. Go ahead

It's ok @anjula-sack , thank you for assign me
