### ISSUE TITLE
Customize the README.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-dev#41]
**Is your feature request related to a problem? Please describe.**
Currently, the README.md file is empty

**Describe the solution you'd like**
Customize the README.md file

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by YoshithaRathnayake** [comment]
Thank you @Piumal1999

**Comment by DilinaBandara** [comment]
Are you still working on this @YoshithaRathnayake ?

**Comment by anjula-sack** [comment]
> Are you still working on this @YoshithaRathnayake ?

I think you can work this.

**Comment by YoshithaRathnayake** [comment]
> Are you still working on this @YoshithaRathnayake ?

Yeah I waiting for a design for this issue

**Comment by YoshithaRathnayake** [comment]
> > Are you still working on this @YoshithaRathnayake ?
> 
> I think you can work this.

@anjula-sack so can you assign me again?

**Comment by DilinaBandara** [comment]
Thanks @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> Thanks @YoshithaRathnayake

Your Welcome @DilinaBandara

**Comment by anjula-sack** [comment]
@DilinaBandara are you working on this?
