### ISSUE TITLE
Increasing text size in SEF website navbar

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-dev#61]
**Describe the bug**
The Navbar text of the SEF site is too small

**To Reproduce**
Go to the SEF webpage to reproduce the bug

**Screenshots**
![image](https://user-images.githubusercontent.com/104125359/183501506-fc8da382-edb5-4961-9ca3-32e21e1a07e4.png)

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
@anjula-sack Can I work on this, please?

**Comment by anjula-sack** [comment]
> @anjula-sack Can I work on this, please?

sure go ahead
